version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  # Serviço do PostgreSQL
  database:
    image: 'postgres:latest'
    networks:
      - broker-kafka
    ports:
      - '15432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_analytics:
    image: postgres:latest
    env_file:
      - .env2  # Segundo banco de dados (analytics)
    volumes:
      - pgdata_analytics:/var/lib/postgresql/data
    ports:
      - "15434:5432"  # Porta diferente para evitar conflito com o primeiro


  # Serviço do PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - broker-kafka
    depends_on:
      - database
      - postgres_analytics
    ports:
      - '15433:80'
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# Definição de volumes persistentes
volumes:
  postgres_data:
  pgadmin_data:
  pgdata_analytics:

networks:
  broker-kafka:
    driver: bridge

