spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:15434/car_post_analytics
    username: myuser
    password: mypassword
    initialization-mode: always
    platform: postgres
    schema: classpath:db/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092


server:
  port: 8084
